version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]
  environment = ["browser"]
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = true
